### ISSUE TITLE
[Bug Report] Error while using Force blend.

### ISSUE THREAD

**Issue by gtr3qq** [PREMIEREHELL/Amulet-Plugins#2]
### Bug Report

I was using this new plugin, and it error-ed out with following notes.
=====================
log begin
=====================
Expecting tag type 10, got 4 instead
Traceback (most recent call last):
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 193, in run_operation
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 85, in show_loading_dialog
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 72, in show_loading_dialog
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 181, in operation_wrapper
  File "D:\Program Files\Amulet\plugins\operations\force_blending.py", line 269, in start
    chunk_data[y_level][v_off:])
  File "D:\Program Files\Amulet\plugins\operations\force_blending.py", line 408, in get_pallets_and_extra
    nbt, p = amulet_nbt.load(pallet_data, little_endian=True, offset=True)
  File "amulet_nbt\amulet_cy_nbt.pyx", line 1098, in amulet_nbt.amulet_cy_nbt.load
amulet_nbt.amulet_cy_nbt.NBTFormatError: Expecting tag type 10, got 4 instead
============================
log end
============================

### Current Behaviour:

 Error-ed out, with debug notes.
### Expected behavior:

 vola, you got your new world.
### Environment:

- OS: Windows 10 21H2 (ver 19044.1766)
- Minecraft Platform: Bedrock
- Minecraft Version: 1.19.2
- Amulet Version: V0.9.6
- plugin version: V1.0

### Screenshots

![image](https://user-images.githubusercontent.com/76813695/177629735-1478b7f9-4751-49ee-b313-7dede5b1821b.png)

### Worlds

...I might be able to via microsoft onedrive.

**Comment by gtr3qq** [comment]
Expecting tag type 10, got 8 instead
Traceback (most recent call last):
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 193, in run_operation
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 85, in show_loading_dialog
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 72, in show_loading_dialog
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 181, in operation_wrapper
  File "D:\Program Files\Amulet\plugins\operations\force_blending.py", line 269, in start
    chunk_data[y_level][v_off:])
  File "D:\Program Files\Amulet\plugins\operations\force_blending.py", line 398, in get_pallets_and_extra
    nbt, p = amulet_nbt.load(pallet_data, little_endian=True, offset=True)
  File "amulet_nbt\amulet_cy_nbt.pyx", line 1098, in amulet_nbt.amulet_cy_nbt.load
amulet_nbt.amulet_cy_nbt.NBTFormatError: Expecting tag type 10, got 8 instead
=======================
different error with V1.01b

**Comment by gtr3qq** [comment]
It appers to be a 1.16 left over problem. 
Author is aware though discord. And is implementing a fix.
