### ISSUE TITLE
NBT_Import_export_plus.py Issue/Bug with the script.

### ISSUE THREAD

**Issue by StealthyExpertX** [PREMIEREHELL/Amulet-Plugins#6]
Traceback (most recent call last):
  File "C:\Users\kidsr\AppData\Local\AmuletTeam\AmuletMapEditor\plugins\operations\NBT_Import_export_plus.py", line 113, in _export_nbt
    {'Properties': amulet_nbt.from_snbt(str(block.properties)),
  File "amulet_nbt\\_load_snbt.pyx", line 210, in amulet_nbt._load_snbt.from_snbt
  File "amulet_nbt\\_load_snbt.pyx", line 214, in amulet_nbt._load_snbt.from_snbt
  File "amulet_nbt\\_load_snbt.pyx", line 212, in amulet_nbt._load_snbt.from_snbt
  File "amulet_nbt\\_load_snbt.pyx", line 113, in amulet_nbt._load_snbt._parse_snbt_recursive
  File "amulet_nbt\\_load_snbt.pyx", line 37, in amulet_nbt._load_snbt._strip_comma
amulet_nbt._errors.SNBTParseError: Expected a comma or } at 20 but got ->("north"), instead

I was given this error when trying to use your plugin to export some entities from my map.

**Comment by StealthyExpertX** [comment]
I also got this error.

Traceback (most recent call last):
  File "C:\Users\kidsr\AppData\Local\AmuletTeam\AmuletMapEditor\plugins\operations\NBT_Import_export_plus.py", line 85, in _export_nbt
    entities = self.get_entities_nbt(block_pos)
  File "C:\Users\kidsr\AppData\Local\AmuletTeam\AmuletMapEditor\plugins\operations\NBT_Import_export_plus.py", line 287, in get_entities_nbt
    nbt_data = amulet_nbt.load(actor, compressed=False, little_endian=True)
  File "amulet_nbt\\_load_nbt.pyx", line 213, in amulet_nbt._load_nbt.load
  File "amulet_nbt\\_load_nbt.pyx", line 130, in amulet_nbt._load_nbt._load_one
  File "amulet_nbt\\_load_nbt.pyx", line 110, in amulet_nbt._load_nbt.load_named_tag
  File "amulet_nbt\\_load_nbt.pyx", line 104, in amulet_nbt._load_nbt.load_tag
  File "amulet_nbt\\_load_nbt.pyx", line 92, in amulet_nbt._load_nbt.load_payload
  File "amulet_nbt\\_compound.pyx", line 55, in amulet_nbt._compound.read_compound_tag
  File "amulet_nbt\\_load_nbt.pyx", line 92, in amulet_nbt._load_nbt.load_payload
  File "amulet_nbt\\_compound.pyx", line 55, in amulet_nbt._compound.read_compound_tag
  File "amulet_nbt\\_load_nbt.pyx", line 92, in amulet_nbt._load_nbt.load_payload
  File "amulet_nbt\\_compound.pyx", line 55, in amulet_nbt._compound.read_compound_tag
  File "amulet_nbt\\_load_nbt.pyx", line 88, in amulet_nbt._load_nbt.load_payload
  File "amulet_nbt\\_string.pyx", line 23, in amulet_nbt._string.read_string_tag
  File "amulet_nbt\\_util.pyx", line 72, in amulet_nbt._util.read_string
UnicodeDecodeError: 'mutf-8' codec can't decode byte 0x00 in position 0: Embedded NULL byte in input.
